services:
  nixos-homepage:
    build:
      context: .
    privileged: true
    environment:
      HOST: "0.0.0.0"
    ports:
      - 4321:4321
    volumes:
      - .:/app
    command:
      - nix
      - develop
      - --command
      - npm
      - run
      - dev